CREATE TABLE IF NOT EXISTS ews_accounts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  username_encrypted VARBINARY(512) NOT NULL,
  password_encrypted VARBINARY(512) NOT NULL,
  ews_server VARCHAR(255) NOT NULL DEFAULT 'owa.mos.ru',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_sessions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  token_hash CHAR(64) NOT NULL UNIQUE,
  ews_account_id INT NOT NULL,
  remember_me BOOLEAN NOT NULL DEFAULT FALSE,
  expires_at DATETIME NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ews_account_id) REFERENCES ews_accounts(id) ON DELETE CASCADE
);
